### ISSUE TITLE
Is keggtools suitable/possible for other organisms than human?

### ISSUE THREAD

**Issue by oseias-r-junior** [harryhaller001/keggtools#2]
Hello,

I'm trying to use KeggTools with an A. thaliana list of genes. I changed some parameters as the original example was fitted for human data and the human Kegg database.

I'm getting an error regarding probably in the parsing of A. thaliana data in Kegg. My question then is:
Is kegg-tools suitable/possible for other organisms than humans (e.g., plants, like Arabidopsis thaliana)?

Next, follows my attempt.

```
ORGANISM_ID = "ath"
resolver = KEGGPathwayResolver(org=ORGANISM_ID)
pathway_id = "04712"
pathway = resolver.get_pathway(code=pathway_id)
study_genes = ["816394","816538","816787","817134"]
analysis = KEGGPathwayAnalysis(org=ORGANISM_ID)
analysis.run_analysis(gene_list=study_genes)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-8c0d6808c92c> in <module>
----> 1 analysis.run_analysis(gene_list=study_genes)

~/.local/lib/python3.6/site-packages/keggtools/analysis.py in run_analysis(self, gene_list)
    225 
    226             genes_found = []
--> 227             all_pathways_genes = pathway.get_genes().keys()
    228             absolute_pathway_genes += len(all_pathways_genes)
    229 

~/.local/lib/python3.6/site-packages/keggtools/models.py in get_genes(self)
    274         for entry in self.entries:
    275             if entry.type == "gene":
--> 276                 result[entry.get_id()] = entry.graphics.name
    277         logging.debug("Get %d unique genes from pathway", len(result.keys()))
    278         return result

~/.local/lib/python3.6/site-packages/keggtools/models.py in get_id(self)
    171         """
    172 
--> 173         return int(self.name.split(":")[1])
    174 
    175 

ValueError: invalid literal for int() with base 10: 'AT2G01140'
```

**Comment by harryhaller001** [comment]
Hello,
with the version `keggtools==0.5.0` the analysis of this organism is not working. The matching of gene identifer only works for entrez ids and the pathway `ath:04712` is using locus tags. This part is currently not well implemented but i'm working on a new version of the package.

The new version is not completely ready yet but you can install it with `pip install git+https://github.com/harryhaller001/keggtools`.

In the new version some of the class names are changed but the following code should work:

```python
from keggtools import Pathway, Renderer, Resolver, Enrichment

resolver: Resolver = Resolver()
pathway: Pathway = resolver.get_pathway(organism="ath", code="04712")

# render steps
renderer: Renderer = Renderer(kegg_pathway=pathway, gene_dict={})
renderer.render(display_unlabeled_genes=True)
open("plot.png", "wb").write(renderer.to_binary(extension="png"))

enricher: Enrichment = Enrichment(pathways=[pathway])

# Use locus tags instead of entrez ids
enricher.run_analysis(gene_list=[
    "AT2G46830",
    "AT1G01060",
    "AT2G46790",
    "AT5G02810",
])

# requires pandas dependency
print(enricher.to_dataframe())
```

Sidenote: The `run_analysis` function performs an enrichment analysis. When analyzing the kegg pathways, it makes most sense to compare several pathways with each other.

**Comment by harryhaller001** [comment]
The new version of the `keggtools` package is released. If you update your version the problem should be fixed. Please note that the class names have changed from version `0.5.0` to `1.0.0`.

**Comment by oseias-r-junior** [comment]
Dear @harryhaller001,
Thanks a lot for letting me know you made a new version of your keggtools.

I have been recently trying to use it again. 
There is something weird I found, though. 

I'm trying to investigate a specific pathway.  For instance, it is the "Pathway path:ath00941 title='Flavonoid biosynthesis'".
I have different datasets (different time points, up or down-regulated genes...). One of these datasets got the following error.

```
># analysis.run_analysis(gene_list=study_genes)
>analysis.run_analysis(gene_list=ath_xfa_3d_up)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-51-8135062b609f> in <module>
      1 # analysis.run_analysis(gene_list=study_genes)
----> 2 analysis.run_analysis(gene_list=ath_xfa_3d_up)

~/.local/lib/python3.6/site-packages/keggtools/analysis.py in run_analysis(self, gene_list)
    241                     [
    242                         [a_var, b_var],
--> 243                         [c_var, d_var],
    244                     ]
    245                 )

~/.local/lib/python3.6/site-packages/scipy/stats/stats.py in fisher_exact(table, alternative)
   3965 
   3966     if np.any(c < 0):
-> 3967         raise ValueError("All values in `table` must be nonnegative.")
   3968 
   3969     if 0 in c.sum(axis=0) or 0 in c.sum(axis=1):

ValueError: All values in `table` must be nonnegative.
```
I did some checking and got the only gene that was supposed to be found in this pathway. Which is 'AT2G40890'. I realized that when I try this gene alone the tool work, but if this gene is among the other genes I get the above-described error message. Those it make sense? Would you think this is also a bug? 
Let me know if you would need more details in order to help me with this issue.
Thanks!

**Comment by harryhaller001** [comment]
Hello,
the parameter `gene_list` must be a list type and can't be just a string.
If you want to test `"AT2G40890"` you have to pass `["AT2G40890"]` to the function.

The code below is working in my environment.
```python
from keggtools import Pathway, Resolver, Enrichment

resolver: Resolver = Resolver()
pathway: Pathway = resolver.get_pathway(organism="ath", code="00941")
enricher: Enrichment = Enrichment(pathways=[pathway])

# Use locus tags
enricher.run_analysis(gene_list=["AT2G40890"])
print(enricher.to_dataframe())
```

I hope this fixes your issue.
