### ISSUE TITLE
Reduce code duplication 

### ISSUE THREAD

**Issue by Nelson-Gon** [harryhaller001/keggtools#4]
While working on #3, I noticed that there are a few lines of code that could be rewritten either as a single method or at least a reusable function written instead. The related code blocks follow the following pattern

```
# get data via the rest API
data = self._cache_or_request(
            filename="organism.tsv",
            url="http://rest.kegg.jp/list/organism",
            **kwargs
        )
# parse file returned 
result = parse_tsv_to_dict(
            data=data,
            col_keys=1,
            col_values=2,
        )
```

In general, this only seems to differ in the url used. I suggest that a single method be written with an argument for example that specifies if the user would like to `compounds` or `organism_list`. This can be done via soft deprecation of existing methods gradually. 

Let me know what you think about this.

Thank you,
NG

**Comment by harryhaller001** [comment]
Hello,
thank you for your suggestions. I agree with you that redundant code can be removed.

**Comment by harryhaller001** [comment]
As you suggested, I have removed some code duplication in the resolver module.

**Comment by Nelson-Gon** [comment]
Awesome, thanks. I will close this as resolved.
