### ISSUE TITLE
Add more pathways

### ISSUE THREAD

**Issue by ondrej-kuda** [harryhaller001/keggtools#5]
Hi, please add more pathways. I cannot compile it using Python 3.10 in Windows. O.

[KEGG_pathway_list_dict.txt](https://github.com/harryhaller001/keggtools/files/9525229/KEGG_pathway_list_dict.txt)

**Comment by harryhaller001** [comment]
Hello,
I can add the additional pathways the package. Thanks for providing the list.
If you have problems executing the code, please consider opening a seperate issue.

**Comment by harryhaller001** [comment]
I have added your list to `keggtools.const` and its published with the version `1.0.1`.
